# Generated by Django 4.2.2 on 2023-07-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_tareaasignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaasignada',
            name='mensaje',
            field=models.CharField(default='Nueva tarea', max_length=100),
        ),
    ]
