# Generated by Django 4.2.2 on 2023-07-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_alter_tarea_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaasignada',
            name='asignado_a',
            field=models.ManyToManyField(to='CRUD.usuariotareas'),
        ),
    ]
