# Generated by Django 4.2.2 on 2023-07-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_alter_tareaasignada_asignado_a'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gruposusuariotareas',
            table='GruposUsuarioTareas',
        ),
        migrations.AlterModelTable(
            name='tarea',
            table='tarea',
        ),
        migrations.AlterModelTable(
            name='tareaasignada',
            table='tarea_asignada',
        ),
        migrations.AlterModelTable(
            name='usuariotareas',
            table='UsuarioTareas',
        ),
    ]
